### PR TITLE
fix #370: GetStatementOfAccountXML receiving multiple CAMT XML files

### LINKED ISSUE #370: GetStatementOfAccountXML receiving multiple CAMT XML files
GetStatementOfAccountXML woks well if the bank is only sending one XML file. 

In case a multiple XML files in arow (e.g each for one days transactions) I get an error. 

> Uncaught InvalidArgumentException: Expected binary block of length 11215, got 46933
> Fhp\Syntax\Parser::parseBinaryBlock('@11215@<?xml ve...')
> Fhp\Syntax\Parser::parseSegmentElement('@11215@<?xml ve...', Object(Fhp\Segment\ElementDescriptor))

The problem is, that the binary block has multiple XMLs in it seperated by "**:**"
@11215@<?xml....>:@22456@<?xml ....>

How can the parser be enhanced to store these XMLs as seperate items?

### PR DESCRIPTION
**Pull request by 2konrad**
The HICAZTest provides two test cases to test parsing of several XMLs that are returned within an HICAZ message by the bank

test 1: two segments seperated by "+" , each containing one XML (currently works fine)
test 2: one of the sgments containing 2 XMLs , seperated by ":" (does not work)

### CODE REVIEW

**Comment by 2konrad** [comment]
I am very happy that these tests finally passed. i am new to this and it took some time to get accustomed to the checking process...

**Comment by ampaze** [comment]
I think, the following line needs to be made compatible with the changes to HICAZv1, so that it always contains a flat array of XML strings

https://github.com/nemiah/phpFinTS/blob/283833cf9cd9f3df595fe596083d60ae988d25a4/lib/Fhp/Action/GetStatementOfAccountXML.php#L172

**Comment by 2konrad** [comment]
yes you are right. There is not test case yet for getGebuchteUmsaetze of GetStatementOfAccountXML, therefor i did not notice that so far. I will look into that.

**Comment by ampaze** [comment]
Thanks, but this will still not result in a flat array of XML strings. 

Could you do something like
```php
foreach ($responseHicaz[0]->getGebuchteUmsaetze()->getData() as $xml) {
 $this->xml[] = $xml; 
}
```
?
This way the consumer of the GetStatementOfAccountXML data can always deal with a single array of xml strings, independend of what a bank sends.

**Comment by ampaze** [comment]
> is that not doing the job? It returns an array of strings.

And is then assigned as another array entry

`$this->xml[] =`

So you end up with an array of array.

**Comment by 2konrad** [comment]
I removed the brackets - now it results in an string array

File: lib/Fhp/Syntax/Bins.php [hunk 1]
```diff
@@ -0,0 +1,29 @@
+<?php
```
Comment (Philipp91) [inline lib/Fhp/Syntax/Bins.php:1]: I'd be in favor of renaming this to `GebuchteCamtUmsaetze` in order to match the specification more closely. If you then move it into the `CAZ` directory, this also allows reverting the change in `BaseDescriptor.php`.

File: lib/Tests/Fhp/Segment/HICAZTest.php [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+
+        $hicaz2 = HICAZv1::parse(static::HICAZ_Test_start .
+                                '@' . strlen(static::sample_XML_doc1) . '@' .
+                                static::sample_XML_doc1 .
+                                ':@' . strlen(static::sample_XML_doc2) . '@' .
+                                static::sample_XML_doc2 .
+                                '+@' . strlen(static::sample_XML_doc3) . '@' .
+                                static::sample_XML_doc3 .
+                                "'");
+        $this->assertEquals(
```
Comment (Philipp91) [inline lib/Tests/Fhp/Segment/HICAZTest.php:70]: How about

```
$this->assertEquals(
           [static::sample_XML_doc1, static::sample_XML_doc2],
           $hicaz2->gebuchteUmsaetze->GetData());
```

That way, this code doesn't crash when the array length is too short, and it points out the bug in case the array is too long.

File: lib/Tests/Fhp/Segment/HICAZTest.php [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+class HICAZTest extends \PHPUnit\Framework\TestCase
+{
+    // Example from FinTS_3.0_Messages_Geschaeftsvorfaelle_2015-08-07_final_version.pdf, Chapter E.7.1 (SIMPLIFIED)
+    // First example: two segments seperated by +
+    // Second example: two segments  seperated by +, first segment has a group of two XMLs seperated by :
+    // According to specification first segmnet has "gebuchte Umsätze", second segment has "vorgemerkte Umsätze"
+    // Inside segemnts several XMLs can be present, seperated by ":"
+
+    private const HICAZ_Test_start = 'HICAZ:5:1:3+DE06940594210000027227:TESTDETT421:::280:+urn?:iso?:std?:iso?:20022?:tech?:xsd?:camt.052.001.02+';
+    private const sample_XML_doc1 = '<?xml version="1.0" encoding="UTF-8"?>' .
```
Comment (Philipp91) [inline lib/Tests/Fhp/Segment/HICAZTest.php:16]: All of these consts' names should be all-caps.

**Comment by Philipp91** [comment]
It's great that you got this working!

**Review by Philipp91 — CHANGES_REQUESTED** [review]
Please link to the issue number from the PR title or description.

**Comment by Philipp91** [comment]
> i am new to this and it took some time to get accustomed to the checking process...

An IDE with auto-formatting functionality helps, and the [cs-fix command](https://github.com/nemiah/phpFinTS#contribute).

File: lib/Fhp/Action/GetStatementOfAccountXML.php [hunk 4]
```diff
@@ -169,6 +169,6 @@ public function processResponse(Message $response)
             throw new UnsupportedException('More than 1 HICAZ response segment is not supported at the moment!');
         }
         // It seems that paginated responses, always contain a whole XML Document
-        $this->xml[] = $responseHicaz[0]->getGebuchteUmsaetze()->getData();
+        $this->xml = $responseHicaz[0]->getGebuchteUmsaetze()->getData();
```
Comment (ampaze) [inline lib/Fhp/Action/GetStatementOfAccountXML.php:172]: The brackets need to stay there, please make a foreach like I suggested.
The it is now it will break on paginated responses.

**Comment by 2konrad** [comment]
In the meantime I tested GetStatementOfAccountXML with Volksbank and Sparkasse - it runs fine so far

**Comment by philippdormann** [comment]
Thanks so much for this PR/ your fork @2konrad , helped me a lot!

What's blocking this from being merged @Philipp91? 🤓

File: lib/Fhp/Syntax/Bins.php (hunk 1 above)
Comment (Philipp91) [reply lib/Fhp/Syntax/Bins.php:1]: I see `GebuchteCamtUmsaetze.php` now. But I also still see this `Bins.php`. Should it be deleted? (Or has it been deleted already, but GitHub continues to show it for some reason?)

File: lib/Fhp/Action/SendSEPADirectDebit.php [hunk 5]
```diff
@@ -166,9 +166,9 @@ protected function createRequest(BPD $bpd, ?UPD $upd)
 
             /* @var HIDMESv1 $hidxes */
             // Just always send the control sum
-            //if ($hidxes->getParameter()->summenfeldBenoetigt) {
+            // if ($hidxes->getParameter()->summenfeldBenoetigt) {
```
Comment (Philipp91) [inline lib/Fhp/Action/SendSEPADirectDebit.php:169]: Should this commented code just be removed entirely?

File: lib/Fhp/Segment/CAZ/GebuchteCamtUmsaetze.php [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+class GebuchteCamtUmsaetze extends BaseDeg
+{
+    /** @var Bin[] @Max(99) */
+    public $gebuchteCamtUmsaetze;
+
+    /**
+     * Array of strings to store XML srings from the Bins structure.
+     * @var string[]
+     */
+    private $xml;
```
Comment (Philipp91) [inline lib/Fhp/Segment/CAZ/GebuchteCamtUmsaetze.php:23]: This seems unused

File: lib/Tests/Fhp/Segment/HICAZTest.php [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+        $hicaz2 = HICAZv1::parse(static::HICAZ_TEST_START .
+                                '@' . strlen(static::SAMPLE_XML_DOC1) . '@' .
+                                static::SAMPLE_XML_DOC1 .
+                                ':@' . strlen(static::SAMPLE_XML_DOC2) . '@' .
+                                static::SAMPLE_XML_DOC2 .
+                                '+@' . strlen(static::SAMPLE_XML_DOC3) . '@' .
+                                static::SAMPLE_XML_DOC3 .
+                                "'");
+        $this->assertEquals([static::SAMPLE_XML_DOC1, static::SAMPLE_XML_DOC2],
+                                $hicaz2->gebuchteUmsaetze->GetData());
```
Comment (Philipp91) [inline lib/Tests/Fhp/Segment/HICAZTest.php:70]: GetData() doesn't exist (with capital G). I think the new getGebuchteUmsaetze() getter should be used here instead.

**Review by Philipp91 — CHANGES_REQUESTED** [review]

**Comment by Philipp91** [comment]
> What's blocking this from being merged 

Sorry, I think there's no notification from GitHub when new commits were pushed, so it would be helpful if you could ping the thread after addressing all the comments (or tell me how to better configure notifications on my end).

**Comment by philippdormann** [comment]
Not a problem 😃

There might still be an issue in this PR.

A successful run looks something like this:
```
</Document>:@5982@<?xml version="1.0" encoding="UTF-8"?><Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02 camt.052.001.02.xsd"><BkToCstmrAcctRpt>...</BkToCstmrAcctRpt></Document>:@3009@<?xml version="1.0" encoding="UTF-8"?><Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02 camt.052.001.02.xsd"><BkToCstmrAcctRpt>...</BkToCstmrAcctRpt></Document>
```
The contents of `BkToCstmrAcctRpt` are obviously redacted but look great 👍

However sometimes I get this error
I think this might be related to the timespan?
```
</Document>
    [224] => @1985@<?xml version="1.0" encoding="UTF-8"?><Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02 camt.052.001.02.xsd"><BkToCstmrAcctRpt>...</BkToCstmrAcctRpt></Document>
    [225] => @5982@<?xml version="1.0" encoding="UTF-8"?><Document xmlns="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:camt.052.001.02 camt.052.001.02.xsd"><BkToCstmrAcctRpt>...</BkToCstmrAcctRpt></Document>
)
 in /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/Syntax/Parser.php:206
Stack trace:
#0 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/Syntax/Parser.php(440): Fhp\Syntax\Parser::parseDeg()
#1 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/Syntax/Parser.php(364): Fhp\Syntax\Parser::parseSegmentElement()
#2 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/Syntax/Parser.php(474): Fhp\Syntax\Parser::parseSegment()
#3 [internal function]: Fhp\Syntax\Parser::detectAndParseSegment()
#4 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/Syntax/Parser.php(491): array_map()
#5 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/Protocol/Message.php(319): Fhp\Syntax\Parser::parseSegments()
#6 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(956): Fhp\Protocol\Message::parse()
#7 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage()
#8 /projects/sandbox/fints/finalStatementOfAccount.php(20): Fhp\FinTs->execute()
#9 {main}

Next Fhp\Syntax\InvalidResponseException: Invalid response from server in /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/FinTs.php:959
Stack trace:
#0 /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage()
#1 /projects/sandbox/fints/finalStatementOfAccount.php(20): Fhp\FinTs->execute()
#2 {main}
  thrown in /projects/sandbox/fints/vendor/nemiah/php-fints/lib/Fhp/FinTs.php on line 959
```
The only difference/ problem is in the separators not being parsed (e.g. `[224] => @1985@`)

Here's the basic code to reproduce this (using the latest commit of this PR: https://github.com/2konrad/phpFinTS/tree/f93e4c69d8190ef9b3065cef39484ce6284bec65):
```
<?php
$fints = require_once 'login.php';
$getSepaAccounts = \Fhp\Action\GetSEPAAccounts::create();
$fints->execute($getSepaAccounts);
if ($getSepaAccounts->needsTan()) {
    handleStrongAuthentication($getSepaAccounts);
}
$account = $getSepaAccounts->getAccounts()[1];
$from = new \DateTime('2021-01-01');
$to = new \DateTime('2022-06-16');
$getStatement = \Fhp\Action\GetStatementOfAccountXML::create($account, $from, $to);
$fints->execute($getStatement);
if ($getStatement->needsTan()) {
    handleStrongAuthentication($getStatement);
}
$bookedXML = $getStatement->getBookedXML();
print_r($bookedXML);
```
When changing from `2021-01-01` to `2022-01-01`, everything works great.

Any idea on this?

**Comment by 2konrad** [comment]
The reason for this problem is most likely the dimension of `class GebuchteCamtUmsaetze extends BaseDeg`. It has a size of 99. 

`/** @var Bin[] @Max(99) */`
`public $gebuchteCamtUmsaetze; `


You are downoading more than 200 XML statements. The banks send one XML per day. If you download more than 99 days, this dimension wont be enough. Can you try to change the `99 `to `299`?

By the way **which bank is that**? The banks i know only send transactions up to 3 months in the past, so 99 was enough.

**Comment by nemiah** [comment]
I'll happily merge this PR as soon as @Philipp91 is fine with it :relaxed:

File: lib/Fhp/Action/SendSEPADirectDebit.php (hunk 5 above)
Comment (2konrad) [reply lib/Fhp/Action/SendSEPADirectDebit.php:169]: I didnt work on SendSEPADirectDebit at all, so difficult for me to tell.

**Comment by philippdormann** [comment]
thanks, @2konrad will try shortly and get back to you with the results

Bank is [Sparkasse Erlangen Höchstadt Herzogenaurach](https://www.sparkasse-erlangen.de/), they give you **510 days** of history 🤓

**Comment by 2konrad** [comment]
@philippdormann can you try now. I increased to 299. We might even go to 510... if it works

**Comment by philippdormann** [comment]
Just tried with the max set to `999`, loading transactions from `2021-01-22` to `2022-06-16` (510 days) now works.

going beyond that (loading from `2021-01-21`), the logger seems fine - resulting array is of length 0 though.

so yeah, we might want to set the max to 510?

this is awesome 🥳

File: lib/Fhp/Syntax/Bins.php (hunk 1 above)
Comment (2konrad) [reply lib/Fhp/Syntax/Bins.php:1]: you are right this can be deleted

File: lib/Tests/Fhp/Segment/HICAZTest.php (hunk 7 above)
Comment (2konrad) [reply lib/Tests/Fhp/Segment/HICAZTest.php:70]: done

File: lib/Fhp/Action/SendSEPADirectDebit.php (hunk 5 above)
Comment (Philipp91) [reply lib/Fhp/Action/SendSEPADirectDebit.php:169]: > I didnt work on SendSEPADirectDebit at all

Then why is it part of this PR? Perhaps you accidentally ran the auto-formatter and would want to revert those changes? Same in MT535.php? (And then squash it all into one commit.)

File: lib/Fhp/Segment/CAZ/GebuchteCamtUmsaetze.php (hunk 6 above)
Comment (Philipp91) [reply lib/Fhp/Segment/CAZ/GebuchteCamtUmsaetze.php:24]: That's a local variable. To reference this `private $xml` from `getData()`, you would have to write `$this->xml` there.

File: lib/Fhp/Segment/CAZ/GebuchteCamtUmsaetze.php [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+
+    /**
+     * Gets the binary data as array of strings.
```
Comment (Philipp91) [inline lib/Fhp/Segment/CAZ/GebuchteCamtUmsaetze.php:27]: If you express this as `@returns string[]`, then many IDEs know how to deal with it. (And the English explanation is then redundant.)

File: lib/Fhp/Segment/CAZ/HICAZv1.php [hunk 9]
```diff
@@ -57,13 +57,13 @@ public function getCamtDescriptor(): string
         return $this->camtDescriptor;
     }
 
-    public function getGebuchteUmsaetze(): Bin
+    public function getGebuchteUmsaetze(): array
```
Comment (Philipp91) [inline lib/Fhp/Segment/CAZ/HICAZv1.php:60]: `/** @returns string[] */`
To help IDEs suggest the right things to users and detect bugs.

**Review by Philipp91 — CHANGES_REQUESTED** [review]

**Comment by 2konrad** [comment]
@Philipp91 reviewed as suggetsed - sorry i tried but i didnt manage to put everything in one commit. I had difficulties resetting the unchanged files ... but now it should be ok

**Comment by nemiah** [comment]
Ok, done, i think :thinking: :blush:

**Comment by 2konrad** [comment]
Thank you - my first pull request 🚀
